### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by ashes-xda** [tonikelope/megadoctor#2]
How do I run it just by clicking MegaDoctor.jar? Please make a tutorial for non coders like me 
I have MegaBasterd already working fine but want to try this MegaCMD GUI as well

![image](https://github.com/tonikelope/megadoctor/assets/24289410/cbd99178-575e-48a4-b62c-99e63f0578fb)

**Comment by tonikelope** [comment]
I recommend OpenJDK 11 or above

 https://adoptium.net

**Comment by ali19833** [comment]
Hi folks,

the .jar file isnt in any folder. At lease i can't find it.,

**Comment by ashes-xda** [comment]
> the .jar file isnt in any folder. At lease i can't find it. And is this supposed to be used for uploads only?
it's a gui for MegaCMD....... For uploads/downloads you should try MegaBasterd (Tip : with proxies)

**Comment by tonikelope** [comment]
megadoctor is a tool designed to manage MEGA account(s) It has some advantages/disadvantages over MegaBasterd. The advantage is that since it uses MEGAcmd underneath, its CPU/RAM resource consumption is lower and in case of updates or changes in MEGA it is transparent since MEGAcmd is officially updated by MEGA. In addition MegaDoctor has two extra features regarding uploads (auto-allocation and split-folders). For those who upload a lot to MEGA I recommend MegaDoctor, but for downloading MegaBasterd.

Regards.

**Comment by ali19833** [comment]
thanks for the excellent explanation mate

**Comment by SaminIIslam** [comment]
new upload button is blank. how to turn it on?

**Comment by tonikelope** [comment]
You need to add an account (and CHECK IT before you can upload).

**Comment by SaminIIslam** [comment]
how do i add an account? I added account to megacmd.

**Comment by tonikelope** [comment]
Add your account in top white textarea and then press big green button
CHECK ACCOUNTS

***@***.***#password

**Comment by SaminIIslam** [comment]
Oh! I got it. Thanks

**Comment by Fakir2023** [comment]
Where is the .jar file located?
